### ISSUE TITLE
TrueVisionGogglesClientHandler

### ISSUE THREAD

**Issue by Girzm** [Wyn-Price/SecretRooms#52]
Below i post the crash i receive upon loading into my server with the latest secret rooms update. Not sure why it happens but wondering if theres a solution, a conflicting mod, or maybe an upcoming patch for this issue.

"	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:mixin,re:classloading}
	at com.wynprice.secretrooms.server.items.TrueVisionGogglesClientHandler.isWearingGoggles(TrueVisionGogglesClientHandler.java:42) ~[?:1.16.5-1.1.2] {re:classloading}
	at com.wynprice.secretrooms.server.items.TrueVisionGogglesClientHandler.onClientWorldTick(TrueVisionGogglesClientHandler.java:28) ~[?:1.16.5-1.1.2] {re:classloading}
	at com.wynprice.secretrooms.SecretRooms6$$Lambda$3946/1516757344.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2845/902790808.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2471/215600582.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreClientTick(BasicEventHooks.java:105) ~[?:?] {re:mixin,re:classloading}
"
FULL CRASH REPORT HERE:

[crash-2021-07-08_02.40.33-client.txt](https://github.com/Wyn-Price/SecretRooms/files/6782194/crash-2021-07-08_02.40.33-client.txt)

**Comment by Girzm** [comment]
Minecraft Version 1.16.5
Forge Version: 36.1.31
Mod Version: secretrooms-1.16.5-1.1.2

**Comment by Girzm** [comment]
never mind i fixed it, dumbo me didnt realize it wasnt installed onto the server. whoops. issue solved
