### ISSUE TITLE
Placing 2 one way glass on top of each other and then breaking them crashes the game

### ISSUE THREAD

**Issue by Nebula240** [Wyn-Price/SecretRooms#60]
As it's shown in the title, if you place 2 rows of one way glass and break the bottom row, resulting in just the top row floating in the air.

This will cause the game to freeze and then crash the client, exiting the game. 

https://paste.ubuntu.com/p/Sq737gtkNg/

This is using the latest version of secret rooms

**Comment by mdonohue** [comment]
Another getPooled NPE

```
java.lang.NullPointerException: Ticking entity
	at com.wynprice.secretrooms.client.world.DelegateWorld.getPooled(DelegateWorld.java:32) ~[?:1.16.5-1.1.3] {re:classloading}
	at com.wynprice.secretrooms.client.world.DelegateWorld.lambda$createFunction$0(DelegateWorld.java:38) ~[?:1.16.5-1.1.3] {re:classloading}

```
