### ISSUE TITLE
[1.16.5] Crash while looking at the top of a Secret Gate with Truesight Goggles

### ISSUE THREAD

**Issue by Catomax262** [Wyn-Price/SecretRooms#63]
Crash Report: https://pastebin.com/dBRg118w

**Comment by mdonohue** [comment]
Looks like another getPooled NPE crash

```
Time: 31/10/21 06:10 PM
Description: Unexpected error
 
java.lang.NullPointerException: Unexpected error
	at com.wynprice.secretrooms.client.world.DelegateWorld.getPooled(DelegateWorld.java:32) ~[?:1.16.5-1.1.3] {re:classloading}
	at com.wynprice.secretrooms.client.world.DelegateWorld.lambda$createFunction$0(DelegateWorld.java:38) ~[?:1.16.5-1.1.3] {re:classloading}

```
