### ISSUE TITLE
1.16.5 crash

### ISSUE THREAD

**Issue by joshualahyt** [Wyn-Price/SecretRooms#67]
it crash,it says opengl 2100/2800 invalid and it save the world and crash

**Comment by joshualahyt** [comment]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 12/24/21 8:09 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.wynprice.secretrooms.client.world.DelegateWorld.getPooled(DelegateWorld.java:32) ~[?:1.16.5-1.1.3] {re:classloading}
	at com.wynprice.secretrooms.server.blocks.states.OneWayGlassState.func_215702_a(OneWayGlassState.java:42) ~[?:1.16.5-1.1.3] {re:classloading}
	at net.minecraft.world.lighting.LightEngine.func_223405_a(LightEngine.java:105) ~[?:?] {re:classloading}
	at net.minecraft.world.lighting.BlockLightEngine.func_215480_b(BlockLightEngine.java:53) ~[?:?] {re:classloading}
	at net.minecraft.world.lighting.BlockLightEngine.func_215477_a(BlockLightEngine.java:101) ~[?:?] {re:classloading}
	at net.minecraft.world.lighting.LevelBasedGraph.func_215474_a(LevelBasedGraph.java:199) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.lighting.LevelBasedGraph.func_215469_a(LevelBasedGraph.java:169) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.lighting.LevelBasedGraph.func_215473_f(LevelBasedGraph.java:164) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.lighting.LightEngine.func_215473_f(LightEngine.java:42) ~[?:?] {re:classloading}
	at net.minecraft.world.lighting.LightEngine.func_215617_a(LightEngine.java:194) ~[?:?] {re:classloading}
	at net.minecraft.world.lighting.WorldLightManager.func_215568_a(SourceFile:30) ~[?:?] {re:classloading}
	at com.wynprice.secretrooms.server.items.SecretBlockItem.doSetBlock(SecretBlockItem.java:55) ~[?:1.16.5-1.1.3] {re:classloading}
	at com.wynprice.secretrooms.server.items.SecretBlockItem.func_195941_b(SecretBlockItem.java:48) ~[?:1.16.5-1.1.3] {re:classloading}
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54) ~[?:?] {re:classloading}
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?] {re:classloading}
	at net.minecraft.item.ItemStack.lambda$useOn$5(ItemStack.java:188) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.item.ItemStack$$Lambda$6844/1345700412.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:203) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:188) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:301) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:97) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1366) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.2.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$437/1893736577.call(Unknown Source) [forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.wynprice.secretrooms.client.world.DelegateWorld.getPooled(DelegateWorld.java:32) ~[?:1.16.5-1.1.3] {re:classloading}
	at com.wynprice.secretrooms.server.blocks.states.OneWayGlassState.func_215702_a(OneWayGlassState.java:42) ~[?:1.16.5-1.1.3] {re:classloading}
	at net.minecraft.world.lighting.LightEngine.func_223405_a(LightEngine.java:105) ~[?:?] {re:classloading}
	at net.minecraft.world.lighting.BlockLightEngine.func_215480_b(BlockLightEngine.java:53) ~[?:?] {re:classloading}
	at net.minecraft.world.lighting.BlockLightEngine.func_215477_a(BlockLightEngine.java:101) ~[?:?] {re:classloading}
	at net.minecraft.world.lighting.LevelBasedGraph.func_215474_a(LevelBasedGraph.java:199) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.lighting.LevelBasedGraph.func_215469_a(LevelBasedGraph.java:169) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.lighting.LevelBasedGraph.func_215473_f(LevelBasedGraph.java:164) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.lighting.LightEngine.func_215473_f(LightEngine.java:42) ~[?:?] {re:classloading}
	at net.minecraft.world.lighting.LightEngine.func_215617_a(LightEngine.java:194) ~[?:?] {re:classloading}
	at net.minecraft.world.lighting.WorldLightManager.func_215568_a(SourceFile:30) ~[?:?] {re:classloading}
	at com.wynprice.secretrooms.server.items.SecretBlockItem.doSetBlock(SecretBlockItem.java:55) ~[?:1.16.5-1.1.3] {re:classloading}
	at com.wynprice.secretrooms.server.items.SecretBlockItem.func_195941_b(SecretBlockItem.java:48) ~[?:1.16.5-1.1.3] {re:classloading}
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54) ~[?:?] {re:classloading}
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?] {re:classloading}
	at net.minecraft.item.ItemStack.lambda$useOn$5(ItemStack.java:188) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.item.ItemStack$$Lambda$6844/1345700412.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:203) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:188) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:301) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:97) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1366) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Joshuamamen'/4, l='ClientLevel', x=-1293.69, y=64.00, z=248.36]]
	Chunk stats: Client Chunk Cache: 121, 30
	Level dimension: minecraft:overworld
	Level spawn location: World: (7,65,-77), Chunk: (at 7,4,3 in 0,-5; contains blocks 0,0,-80 to 15,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 6845 game time, 1 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.2.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$437/1893736577.call(Unknown Source) [forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6470748760 bytes (6170 MB) / 7348420608 bytes (7008 MB) up to 7348420608 bytes (7008 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmn128M -Xmx7000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.2.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.2
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.2-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.2-universal.jar                 |Forge                         |forge                         |36.2.2              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		worldedit-mod-7.2.5-dist (1).jar                  |WorldEdit                     |worldedit                     |7.2.5+57d5ac9       |DONE      |Manifest: NOSIGNATURE
		tl_skin_cape_forge_1.16.5-1.19.jar                |TLSkinCape                    |tlskincape                    |1.19                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		secretrooms-1.16.5-1.1.3 (2).jar                  |Secret Rooms 6                |secretroomsmod                |1.16.5-1.1.3        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: fae5cefc-9475-47df-95be-83f89e08c85c
	Launched Version: ForgeOptiFine 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) RX Vega 10 Graphics  GL version 4.6.14761 Compatibility Profile Context 21.11.3 30.0.13037.1003, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: programer_art, programer_art
	Current Language: English (United Kingdom)
	CPU: 8x AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx 
	OptiFine Version: OptiFine_1.16.5_HD_U_G8_pre2
	OptiFine Build: 20210305-002749
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14761 Compatibility Profile Context 21.11.3 30.0.13037.1003
	OpenGlRenderer: AMD Radeon(TM) RX Vega 10 Graphics 
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by mdonohue** [comment]
It looks like the static ArrayList "AVAILABLE" isn't consistently protected by a lock when it is accessed.  I'm not familiar with minecraft mods, so I will look at how to build this mod to test a fix.
