### ISSUE TITLE
Strange Crash

### ISSUE THREAD

**Issue by jamesipod** [Wyn-Price/SecretRooms#70]
1.18.1, Latest forge, getting this error on my server:

[18:18:22] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.wynprice.secretrooms.server.tileentity.SecretTileEntity.save(net.minecraft.nbt.CompoundTag)'
	at com.wynprice.secretrooms.server.tileentity.SecretTileEntity.m_5995_(SecretTileEntity.java:45) ~[secretrooms-1.18.1-1.1.4.jar%2390!/:1.18.1-1.1.4]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:153) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1125) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:785) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.level.ChunkMap.sendChunks(ChunkMap.java:2343) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.level.ChunkMap.m_140184_(ChunkMap.java:2317) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8385_(ServerChunkCache.java:448) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7185_(ServerGamePacketListenerImpl.java:850) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.m_5797_(ServerboundMovePlayerPacket.java:114) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.m_5797_(ServerboundMovePlayerPacket.java:16) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23101!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by jamesipod** [comment]
It's definitely from placing down items from Secretrooms, I placed down a secret iron door and crashed again.

**Comment by Wyn-Price** [comment]
What other mods do you have? This looks like a weird bug. Could you upload the whole crashlog

**Comment by jamesipod** [comment]
I think the mod has to be updated to Forge 39.0,46+. Some other mods had to do the same thing. and had a very similar crash log. 
https://forums.minecraftforge.net/topic/108028-keeps-crashing/
https://forums.minecraftforge.net/topic/108529-game-crash-with-forge-39066-390064/
https://forums.minecraftforge.net/topic/108029-my-game-closed-when-i-placed-a-block-and-i-cannot-join-the-world-anymore/

**Comment by PatTheWizard** [comment]
I had a similar crash as well. I was flying around in an elytra when i got hit with it and then it would crash upon me trying to get back into the world

**Comment by hacheraw** [comment]
Same crash five minutes after crafting and placing secret pression plates

```
[02:23:17] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.wynprice.secretrooms.server.tileentity.SecretTileEntity.save(net.minecraft.nbt.CompoundTag)'
	at com.wynprice.secretrooms.server.tileentity.SecretTileEntity.m_5995_(SecretTileEntity.java:45) ~[secretrooms-1.18.1-1.1.4.jar%23130!/:1.18.1-1.1.4]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:153) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1125) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:785) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.level.ChunkMap.m_140184_(ChunkMap.java:990) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8385_(ServerChunkCache.java:448) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5659_(ServerGamePacketListenerImpl.java:392) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.network.protocol.game.ServerboundMoveVehiclePacket.m_5797_(ServerboundMoveVehiclePacket.java:41) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.network.protocol.game.ServerboundMoveVehiclePacket.m_5797_(ServerboundMoveVehiclePacket.java:7) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:110) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23149!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

1.18.1
Forge 39.50.75

Mods installed:

```
.rwxrwxrwx   97k hache 10 Feb 19:01  Actually Useful Stonecutter-3.0.0 mc 1.18.1.jar*
.rwxrwxrwx   18k hache 10 Feb 19:10  AirAffinity-1.18.1-1.0.0.jar*
.rwxrwxrwx  3.9M hache 10 Feb 19:39  Alex's Mobs Mod Music.jar*
.rwxrwxrwx   22M hache 10 Feb 19:39  alexsmobs-1.17.0.jar*
.rwxrwxrwx  241k hache 10 Feb 19:47  Amplified Nether 1.0.1 ~ Forge.jar*
.rwxrwxrwx   46k hache 10 Feb 19:23  appleskin-forge-mc1.18-2.3.0.jar*
.rwxrwxrwx  569k hache 10 Feb 19:32  Aquaculture-1.18.1-2.3.2.jar*
.rwxrwxrwx  488k hache 10 Feb 19:08  artifacts-1.18.1-4.0.2.jar*
.rwxrwxrwx   43k hache 10 Feb 19:06  AutoRegLib-1.7-53.jar*
.rwxrwxrwx  504k hache 10 Feb 20:39  awesomedungeon-2.0.5.jar*
.rwxrwxrwx  188k hache 10 Feb 19:51  AwesomeDungeonNether-Forge-1.18.1-1.0.0.jar*
.rwxrwxrwx  327k hache 10 Feb 20:39  AwesomeDungeonOcean-Forge-1.18-2.0.4.jar*
.rwxrwxrwx  609k hache 10 Feb 18:48  balm-2.4.2+0.jar*
.rwxrwxrwx  528k hache 10 Feb 19:47  BasicNetherOres-1.18.1-7.1.2.jar*
.rwxrwxrwx   78k hache 10 Feb 18:43  BetterModsButton-v3.1.0-1.18.1-Forge.jar*
.rwxrwxrwx   16k hache 10 Feb 19:52  BetterPingDisplay-1.18.1-1.1.jar*
.rwxrwxrwx  6.6k hache 10 Feb 19:52  betterspawnercontrol_1.18.1-1.6.jar*
.rwxrwxrwx   21M hache 10 Feb 19:01  BiomesOPlenty-1.18.1-15.0.0.104-universal.jar*
.rwxrwxrwx   37k hache 10 Feb 20:36  caelus-forge-1.18-3.0.0.1.jar*
.rwxrwxrwx  319k hache 10 Feb 19:08  carryon-1.18.1-1.17.0.7.jar*
.rwxrwxrwx  146k hache 10 Feb 18:56  chalk-1.18.1-1.2.0.jar*
.rwxrwxrwx  437k hache 10 Feb 19:15  chococraft-1.18.1-0.2.3.jar*
.rwxrwxrwx  502k hache 10 Feb 19:39  citadel-1.10.10-1.18.jar*
.rwxrwxrwx  114k hache 10 Feb 18:48  clienttweaks-forge-1.18-7.0.0.jar*
.rwxrwxrwx   10k hache 10 Feb 18:45  Clumps-forge-1.18.1-8.0.0+5.jar*
.rwxrwxrwx  142k hache 10 Feb 19:05  collective-1.18.1-4.0.jar*
.rwxrwxrwx  246k hache 10 Feb 18:43  ConfigMenusForge-v3.1.0-1.18.1-Forge.jar*
.rwxrwxrwx  653k hache 10 Feb 18:49  cookingforblockheads-forge-1.18.1-11.1.0.jar*
.rwxrwxrwx  239k hache 10 Feb 18:55  corail_recycler-5.5.0-1.18.1.jar*
.rwxrwxrwx   88k hache 10 Feb 19:29  CosmeticArmorReworked-1.18.1-v1a.jar*
.rwxrwxrwx  1.3M hache 10 Feb 19:40  Croptopia-1.18-FORGE-1.8.0.jar*
.rwxrwxrwx  254k hache 10 Feb 19:05  curios-forge-1.18.1-5.0.6.0.jar*
.rwxrwxrwx   29k hache 10 Feb 19:06  CuriosQuarkOBP-1.18.1-1.1.0.jar*
.rwxrwxrwx   55k hache 10 Feb 20:21  DisenchantmentEditTable-1.18-1.0.5.jar*
.rwxrwxrwx  5.4M hache 10 Feb 19:42  DungeonsArise-1.18.1-2.1.49d-beta.jar*
.rwxrwxrwx   36k hache 10 Feb 20:22  dynamiclights-1.18.2.jar*
.rwxrwxrwx   15k hache 10 Feb 19:03  dynview-1.18.1-2.4.jar*
.rwxrwxrwx  192k hache 10 Feb 18:49  EasyEmerald-Forge-1.18.1-1.3.7.jar*
.rwxrwxrwx  352k hache 10 Feb 19:39  EasySteel-Forge-1.18.1-1.5.12.jar*
.rwxrwxrwx  186k hache 10 Feb 18:49  elevatorid-1.18-1.8.3.jar*
.rwxrwxrwx   57k hache 10 Feb 19:30  EnchantmentDescriptions-Forge-1.18.1-9.0.11.jar*
.rwxrwxrwx   45k hache 10 Feb 18:47  entityculling-forge-mc1.18-1.5.0.jar*
.rwxrwxrwx   43k hache 10 Feb 19:08  expandability-5.0.0-forge.jar*
.rwxrwxrwx   15k hache 10 Feb 19:34  feature_nbt_deadlock_be_gone_forge-1.0.0+1.18.1.jar*
.rwxrwxrwx  4.8k hache 10 Feb 19:33  flatbedrock-1.4.1-build.8+mc1.18.1.jar*
.rwxrwxrwx  2.1M hache 10 Feb 19:02  furniture-7.0.0-pre28-1.18.1.jar*
.rwxrwxrwx  2.8M hache 10 Feb 19:45  geckolib-1.18-forge-3.0.11.jar*
.rwxrwxrwx  429k hache 10 Feb 19:44  goblintraders-1.7.0-1.18.1.jar*
.rwxrwxrwx  245k hache 10 Feb 19:05  gravestone-1.18.1-1.0.2.jar*
.rwxrwxrwx  108k hache 10 Feb 19:55  howlingmoon rebooted-0.9.2.1.jar*
.rwxrwxrwx  127k hache 10 Feb 19:40  HunterIllager-1.18.1-3.1.6.jar*
.rwxrwxrwx  267k hache 10 Feb 19:19  Jade-1.18-4.1.2.jar*
.rwxrwxrwx   66k hache 10 Feb 19:23  jeed-1.18.1-1.7.jar*
.rwxrwxrwx  916k hache 11 Feb 21:27  jei-1.18.1-9.3.2.92.jar*
.rwxrwxrwx   25k hache 10 Feb 19:25  jepp-1.18-1.0.0.jar*
.rwxrwxrwx  6.9M hache 10 Feb 19:20  journeymap-1.18.1-5.8.0beta14.jar*
.rwxrwxrwx   13k hache 10 Feb 19:23  JRFTL [1.18.1]-1.4.1.jar*
.rwxrwxrwx   42k hache 10 Feb 19:25  JustEnoughAdvancements-1.18.1-3.1.0.jar*
.rwxrwxrwx  135k hache 10 Feb 19:25  JustEnoughDrugz-0.8.1.jar*
.rwxrwxrwx   19k hache 10 Feb 19:23  JustEnoughProfessions-1.18-1.2.2.jar*
.rwxrwxrwx  245k hache 10 Feb 19:23  JustEnoughResources-1.18.1-0.13.1.150.jar*
.rwxrwxrwx   40k hache 10 Feb 19:56  justmobheads_1.18.1-5.3.jar*
.rwxrwxrwx  284k hache 10 Feb 19:11  kleeslabs-forge-1.18.1-11.0.1.jar*
.rwxrwxrwx   15k hache 10 Feb 18:47  lazydfu-1.0-1.18+.jar*
.rwxrwxrwx  7.3k hache 10 Feb 19:51  LibraryFerret-Forge-1.18.1-1.0.3.jar*
.rwxrwxrwx  809k hache 10 Feb 19:25  LibX-1.18.1-3.1.0.jar*
.rwxrwxrwx  1.4M hache 11 Feb 21:27  lightmanscurrency-1.18-1.0.3.4.jar*
.rwxrwxrwx  7.6M hache 10 Feb 19:01  macawsbridgesbop-1.18.1-1.0.jar*
.rwxrwxrwx  4.9M hache 11 Feb 21:27  MCDoom-1.18.1-4.1.10.jar.disabled*
.rwxrwxrwx  661k hache 10 Feb 19:01  mcw-bridges-2.0.1-mc1.18.1.jar*
.rwxrwxrwx  870k hache 10 Feb 19:01  mcw-doors-1.0.5-mc1.18.1.jar*
.rwxrwxrwx  798k hache 10 Feb 19:01  mcw-windows-2.0.2-mc1.18.1.jar*
.rwxrwxrwx   20k hache 10 Feb 18:54  Measurements-1.18-1.2.jar*
.rwxrwxrwx  607k hache 10 Feb 18:56  mininggadgets-1.10.2.jar*
.rwxrwxrwx  2.8M hache 10 Feb 18:58  moblocks-0.10.1b.jar*
.rwxrwxrwx  3.9M hache 10 Feb 18:49  modernlife-1.18.1-1.31.jar*
.rwxrwxrwx   12k hache 10 Feb 19:27  modnametooltip-1.18.1-1.18.0.jar*
.rwxrwxrwx  200k hache 10 Feb 22:12  mores-1.2.0.jar*
.rwxrwxrwx  283k hache 10 Feb 19:34  morevillagers-FORGE-1.18.1-3.1.2.jar*
.rwxrwxrwx  342k hache 10 Feb 19:05  Nameless Trinkets-1.18.1-1.3.4.jar*
.rwxrwxrwx  203k hache 10 Feb 18:50  NaturesCompass-1.18.1-1.9.4-forge.jar*
.rwxrwxrwx   33k hache 10 Feb 19:48  netherelytra-1.1.0-1.18.1-curios.jar*
.rwxrwxrwx  216k hache 10 Feb 19:46  netherportalfix-forge-1.18-9.0.0.jar*
.rwxrwxrwx   21k hache 10 Feb 19:48  netherportalspread_1.18.1-5.7.jar*
.rwxrwxrwx   11k hache 10 Feb 19:34  no_null_processors_forge-2.0.2+1.18.1.jar*
.rwxrwxrwx   36k hache 10 Feb 18:55  ObsidianBoat-1.2.1-build.10+mc1.18.1.jar*
.rwxrwxrwx  6.5M hache 10 Feb 21:39  OptiFine_1.18.1_HD_U_H4.jar*
.rwxrwxrwx  461k hache 10 Feb 19:08  Paint Palettes 1.18.1 Forge 39.0.66.jar*
.rwxrwxrwx   77k hache 10 Feb 19:30  PickUpNotifier-v3.1.0-1.18.1-Forge.jar*
.rwxrwxrwx  106k hache 11 Feb 21:27  PuzzlesLib-v3.1.5-1.18.1-Forge.jar*
.rwxrwxrwx   12M hache 10 Feb 19:06  Quark-3.0-334.jar*
.rwxrwxrwx  1.9k hache 10 Feb 19:06  QuarkOddities-1.18.jar*
.rwxrwxrwx   94k hache 10 Feb 19:33  Regrowth-1.18.1-1.39.0.26.jar*
.rwxrwxrwx  5.9M hache 10 Feb 19:34  repurposed_structures_forge-4.2.9+1.18.1.jar*
.rwxrwxrwx   16k hache 10 Feb 18:47  screenshot-to-clipboard-1.0.9-forge.jar*
.rwxrwxrwx  244k hache 10 Feb 18:56  secretrooms-1.18.1-1.1.4.jar*
.rwxrwxrwx  136k hache 10 Feb 19:32  SereneSeasons-1.18.1-6.0.0.10-universal.jar*
.rwxrwxrwx   13k hache 10 Feb 19:54  smallernetherportals_1.18.1-1.9.jar*
.rwxrwxrwx  9.2k hache 10 Feb 19:05  stackrefill_1.18.1-2.1.jar*
.rwxrwxrwx  578k hache 10 Feb 18:51  StorageDrawers-1.18.1-10.1.1.jar*
.rwxrwxrwx   23k hache 10 Feb 19:11  swingthroughgrass-1.18.1-1.8.0.jar*
.rwxrwxrwx  713k hache 10 Feb 18:43  Teletubbies-1.18.1-9.0.2.jar*
.rwxrwxrwx  176k hache 10 Feb 19:01  TerraBlender-forge-1.18.1-1.1.0.73.jar*
.rwxrwxrwx  1.1M hache 10 Feb 19:43  TerraForged-1.18.1-0.3.0-alpha-2.jar*
.rwxrwxrwx  112k hache 10 Feb 19:30  trashslot-forge-1.18-11.0.1.jar*
.rwxrwxrwx  263k hache 10 Feb 19:05  TreeChop-1.18.1-0.15.5.jar*
.rwxrwxrwx  104k hache 10 Feb 19:05  TreePlant-1.18.1-0.3.0.jar*
.rwxrwxrwx  402k hache 10 Feb 18:57  u_team_core-1.18.1-4.0.0.201-SNAPSHOT.jar*
.rwxrwxrwx   13k hache 10 Feb 19:47  upgradedcore-1.18.1-3.0.0.0-release.jar*
.rwxrwxrwx  985k hache 11 Feb 21:27  upgradednetherite-1.18.1-4.0.0.1-release.jar*
.rwxrwxrwx  175k hache 10 Feb 18:57  useful_backpacks-1.18.1-1.12.1.92-SNAPSHOT.jar.disabled*
.rwxrwxrwx  342k hache 10 Feb 19:32  waystones-forge-1.18.1-9.0.3.jar*
.rwxrwxrwx   18k hache 10 Feb 19:10  xptome-1.18-2.1.3.jar*
```
